In [1]:
import pandas as pd
from sqlalchemy import create_engine
from config import db_password

In [2]:
abortions_df = pd.read_excel("Resources/Partially_Cleaned_Data/GuttmacherDataCenter.xlsx", 
                                       skiprows=[52,53,54], 
                                       index_col='U.S. State')
abortions_df = abortions_df.rename(columns={"U.S. State": "State",
                                            "% of all U.S. abortions, by state of occurrence, 2020":"percent_of_all_us_abortions", 
                                           "% of residents obtaining abortions who traveled out of state for care, 2020": "percent_residents_traveling_outside_state",
                                           "No. of abortions, by state of occurrence, 2020 [1]": "abortions_occurring_state",
                                           "No. of abortions, by state of residence, 2020 [2]": "abortions_residence_state"})
abortions_df

,percent_of_all_us_abortions,percent_residents_traveling_outside_state,abortions_occurring_state,abortions_residence_state
U.S. State,,,,
Alabama,0.6,47,"5,700","9,060"
Alaska,0.1,7,"1,240","1,320"
Arizona,1.4,6,"13,320","13,820"
Arkansas,0.3,37,"3,250","4,510"
California,16.6,0,"154,060","152,400"
Colorado,1.4,1,"13,420","11,830"
Connecticut,1.2,6,"11,170","11,460"
Delaware,0.2,44,"1,830","2,870"
District of Columbia,1.0,45,"9,410","5,010"
Florida,8.3,1,"77,400","73,830"
Georgia,4.5,5,"41,620","36,470"
Hawaii,0.3,2,"3,130","3,120"
Idaho,0.2,26,"1,690","2,130"
Illinois,5.7,1,"52,780","42,250"
Indiana,0.8,31,"7,880","10,810"
Iowa,0.4,12,"3,510","3,510"
Kansas,0.9,4,"8,180","4,120"
Kentucky,0.4,39,"4,080","5,690"
Louisiana,0.8,21,"7,360","7,760"
Maine,0.3,5,"2,370","2,370"
Maryland,3.3,17,"30,750","29,590"
Massachusetts,1.8,6,"17,060","17,460"
Michigan,3.4,1,"31,500","30,150"
Minnesota,1.2,3,"11,060","10,380"
Mississippi,0.4,44,"3,560","5,760"
Missouri,0.0,99,170,"11,710"
Montana,0.2,3,"1,630","1,510"
Nebraska,0.2,8,"2,200","2,020"
Nevada,1.2,4,"11,010","10,870"
New Hampshire,0.2,23,"2,050","2,150"
New Jersey,5.2,6,"48,830","48,390"
New Mexico,0.6,8,"5,880","3,950"
New York,11.9,1,"110,360","105,990"
North Carolina,3.4,2,"31,850","27,030"
North Dakota,0.1,13,"1,170",960
Ohio,2.3,10,"20,990","21,920"
Oklahoma,1.0,5,"9,690","8,330"
Oregon,0.9,5,"8,560","8,110"
Pennsylvania,3.5,14,"32,260","34,950"
Rhode Island,0.3,17,"2,760","2,830"
South Carolina,0.6,57,"5,300","11,830"
South Dakota,0.0,84,130,680
Tennessee,1.2,23,"10,850","10,450"
Texas,6.2,8,"58,020","61,500"
Utah,0.3,8,"3,120","3,220"
Vermont,0.1,7,"1,230","1,100"
Virginia,2.0,25,"18,740","23,390"
Washington,1.9,5,"17,980","17,910"
West Virginia,0.1,52,990,"1,780"
Wisconsin,0.7,17,"6,960","8,290"
Wyoming,0.0,88,100,700

In [3]:
abortions_df['abortions_occurring_state'] = abortions_df['abortions_occurring_state'].str.replace(',', '')
abortions_df['abortions_residence_state'] = abortions_df['abortions_residence_state'].str.replace(',', '')
abortions_df.index.names = ['state']
abortions_df.head()

,percent_of_all_us_abortions,percent_residents_traveling_outside_state,abortions_occurring_state,abortions_residence_state
state,,,,
Alabama,0.6,47,5700,9060
Alaska,0.1,7,1240,1320
Arizona,1.4,6,13320,13820
Arkansas,0.3,37,3250,4510
California,16.6,0,154060,152400

In [7]:
pd.DataFrame.to_csv(abortions_df, 'abortions.csv', sep=',', na_rep='.', index=True)

In [4]:
db_string = f"postgresql://postgres:{db_password}@127.0.0.1:5433/Reproducitve_Access"
engine = create_engine(db_string)
abortions_df.to_sql(name='abortions_data', con=engine)