# Machine Learning
### Input variables
### State abortion policy as of 8/7/22 
### State Community Health Centers
### Health insurance coverage of women
### Maternal death and mortality rates
### Legal abortions obtained out of state
### Legal abortions obtained in state of occurence
### Population distribution by sex
### Reported women not seeing a doctor in past 12 months
### Reported women having a mammogram in last 2 years
### Reported women not having a personal doctor or health care provider
### Reported women having a pap smear in the last 3 years
### State requirements for insurance coverage of contraceptives
### Poverty

In [1]:
import pandas as pd
from sqlalchemy import create_engine
from config import db_password

C:\Users\nikki\Anaconda3\envs\PythonData\lib\site-packages\numpy\__init__.py:143: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init

ImportError: Unable to import required dependencies:
numpy:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "C:\Users\nikki\Anaconda3\envs\PythonData\python.exe"
  * The NumPy version is: "1.20.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed: The specified module could not be found.

In [2]:
abortion_status_df = pd.read_csv("All_States_Abortion_Policy_Tracker.csv", 
                                        skiprows=[0,1,3,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80],
                                        index_col='Location')
abortion_status_df = abortion_status_df.drop(columns='Footnotes')
abortion_status_df = abortion_status_df.rename(columns={"Status of Abortion": "Abortion_Status"})
abortion_status_df

                                                        Abortion_Status
Location
Alabama                                          Abortion Ban In Effect
Alaska                                               Abortion Available
Arizona                                   Status of pre-Roe ban unclear
Arkansas                                         Abortion Ban In Effect
California                                           Abortion Available
Colorado                                             Abortion Available
Connecticut                                          Abortion Available
Delaware                                             Abortion Available
District of Columbia                                 Abortion Available
Florida               Abortion available, pre-viability gestational ...
Georgia                              6 week LMP ban currently in effect
Hawaii                                               Abortion Available
Idaho                 State abortion ban/restriction not yet impleme...
Illinois                                             Abortion Available
Indiana               Abortion available, pre-viability gestational ...
Iowa                  Abortion available, pre-viability gestational ...
Kansas                Abortion available, pre-viability gestational ...
Kentucky                                         Abortion Ban In Effect
Louisiana                                        Abortion Ban In Effect
Maine                                                Abortion Available
Maryland                                             Abortion Available
Massachusetts                                        Abortion Available
Michigan                                             Abortion Available
Minnesota                                            Abortion Available
Mississippi                                      Abortion Ban In Effect
Missouri                                         Abortion Ban In Effect
Montana                                              Abortion Available
Nebraska              Abortion available, pre-viability gestational ...
Nevada                                               Abortion Available
New Hampshire                                        Abortion Available
New Jersey                                           Abortion Available
New Mexico                                           Abortion Available
New York                                             Abortion Available
North Carolina                                       Abortion Available
North Dakota          State abortion ban/restriction not yet impleme...
Ohio                                 6 week LMP ban currently in effect
Oklahoma                                         Abortion Ban In Effect
Oregon                                               Abortion Available
Pennsylvania                                         Abortion Available
Rhode Island                                         Abortion Available
South Carolina                       6 week LMP ban currently in effect
South Dakota                                     Abortion Ban In Effect
Tennessee                            6 week LMP ban currently in effect
Texas                                            Abortion Ban In Effect
Utah                  Abortion ban temporarily blocked, abortion ava...
Vermont                                              Abortion Available
Virginia                                             Abortion Available
Washington                                           Abortion Available
West Virginia         Abortion ban temporarily blocked, abortion ava...
Wisconsin                                 Status of pre-Roe ban unclear
Wyoming               Abortion ban temporarily blocked, abortion ava...

In [3]:
CHC_df = pd.read_csv("Community_Health_Center_Delivery_Sites_and_Patient_Visits.csv", 
                                        skiprows=[0,1,3,42,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79],
                                        index_col='Location')
CHC_df = CHC_df.drop(columns='Footnotes')
CHC_df = CHC_df.rename(columns={"Total CHCs": "Total_Community_Health_Centers"})
CHC_df

                      Total_Community_Health_Centers
Location
Alabama                                           17
Alaska                                            27
Arizona                                           23
Arkansas                                          12
California                                       175
Colorado                                          19
Connecticut                                       16
Delaware                                           3
District of Columbia                               8
Florida                                           47
Georgia                                           35
Hawaii                                            14
Idaho                                             14
Illinois                                          45
Indiana                                           27
Iowa                                              14
Kansas                                            19
Kentucky                                          25
Louisiana                                         36
Maine                                             18
Maryland                                          17
Massachusetts                                     37
Michigan                                          39
Minnesota                                         16
Mississippi                                       20
Missouri                                          28
Montana                                           14
Nebraska                                           7
Nevada                                             8
New Hampshire                                     10
New Jersey                                        23
New Mexico                                        16
New York                                          63
North Carolina                                    39
North Dakota                                       4
Ohio                                              51
Oklahoma                                          21
Oregon                                            30
Pennsylvania                                      42
Rhode Island                                       8
South Carolina                                    23
South Dakota                                       4
Tennessee                                         29
Texas                                             72
Utah                                              13
Vermont                                           11
Virginia                                          26
Washington                                        27
West Virginia                                     28
Wisconsin                                         16
Wyoming                                            6

In [4]:
ins_df = pd.read_csv("Health_Ins_Coverage_of_Women_19-64_in_2020.csv", 
                         skiprows=[0,1,3,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81], 
                         index_col='Location')
ins_df = ins_df.drop(columns=['Employer', 'Non-Group', 'Medicaid', 'Medicare', 'Military'])
ins_df = ins_df.rename(columns={"Total":"Total_Insured"})
ins_df

                      Uninsured  Total_Insured
Location
Alabama                  165700        1462900
Alaska                    29200         207200
Arizona                  309000        2132900
Arkansas                  83800         865900
California              1034300       11885100
Colorado                 204300        1758600
Connecticut               58100        1038000
Delaware                  24800         295800
District of Columbia       7600         251600
Florida                 1011800        6381600
Georgia                  586000        3356300
Hawaii                    18900         379800
Idaho                     78900         535000
Illinois                 328700        3731700
Indiana                  131100        1957600
Iowa                      72800         927300
Kansas                    93200         827300
Kentucky                 101400        1305500
Louisiana                133400        1376800
Maine                     24400         398100
Maryland                  91400        1838500
Massachusetts             75000        2146900
Michigan                 126300        2918800
Minnesota                107600        1650900
Mississippi              117200         884200
Missouri                 202800        1773100
Montana                   26300         300200
Nebraska                  53000         558300
Nevada                   116600         939300
New Hampshire             19300         379800
New Jersey               208000        2620400
New Mexico                83500         589200
New York                 258400        5854500
North Carolina           397100        3231100
North Dakota              17900         212500
Ohio                     241800        3353800
Oklahoma                 241200        1135800
Oregon                    62600        1260900
Pennsylvania             230100        3755700
Rhode Island              12700         325800
South Carolina           186400        1530800
South Dakota              24400         239200
Tennessee                283100        2068800
Texas                   1929400        8727300
Utah                     108800         932000
Vermont                    5600         176300
Virginia                 211200        2710400
Washington               203300        2369200
West Virginia             31100         498100
Wisconsin                105600        1783100
Wyoming                   19100         160600

In [5]:
maternal_deaths_df = pd.read_csv("Maternal_deaths_and_mortality_rates.csv", 
                                    skiprows=[0,1,3,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69], 
                                    index_col='Location')
maternal_deaths_df = maternal_deaths_df.drop(columns=['Maternal Mortality Rate per 100,000 live Births'])
maternal_deaths_df = maternal_deaths_df.rename(columns={"Number of Deaths": "Number Maternal Deaths"})
maternal_deaths_df

                      Number Maternal Deaths
Location
Alabama                                   63
Alaska                                     8
Arizona                                   67
Arkansas                                  44
California                               135
Colorado                                  27
Connecticut                               18
Delaware                                   5
District of Columbia                       7
Florida                                  141
Georgia                                  108
Hawaii                                     7
Idaho                                     11
Illinois                                  54
Indiana                                   68
Iowa                                      14
Kansas                                    23
Kentucky                                  63
Louisiana                                 56
Maine                                      3
Maryland                                  39
Massachusetts                             30
Michigan                                  63
Minnesota                                 19
Mississippi                               33
Missouri                                  54
Montana                                    8
Nebraska                                  21
Nevada                                    20
New Hampshire                              2
New Jersey                                72
New Mexico                                10
New York                                 133
North Carolina                            73
North Dakota                               7
Ohio                                      85
Oklahoma                                  36
Oregon                                    18
Pennsylvania                              60
Rhode Island                               5
South Carolina                            49
South Dakota                               7
Tennessee                                 83
Texas                                    257
Utah                                      17
Vermont                                    1
Virginia                                  65
Washington                                52
West Virginia                             12
Wisconsin                                 17
Wyoming                                    3

In [6]:
total_births_df = pd.read_csv("Total_Number_of_Births.csv", 
                                    skiprows=[0,1,3,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72], 
                                    index_col='Location')
total_births_df = total_births_df.drop(columns='Footnotes')
total_births_df['Number of Births'] = total_births_df['Number of Births'].str.replace(',', '')
total_births_df

                     Number of Births
Location
Alabama                         57647
Alaska                           9469
Arizona                         76947
Arkansas                        35251
California                     420259
Colorado                        61494
Connecticut                     33460
Delaware                        10392
District of Columbia             8874
Florida                        209671
Georgia                        122473
Hawaii                          15785
Idaho                           21533
Illinois                       133298
Indiana                         78616
Iowa                            36114
Kansas                          34376
Kentucky                        51668
Louisiana                       57328
Maine                           11539
Maryland                        68554
Massachusetts                   66428
Michigan                       104074
Minnesota                       63443
Mississippi                     35473
Missouri                        69285
Montana                         10791
Nebraska                        24291
Nevada                          33653
New Hampshire                   11791
New Jersey                      97954
New Mexico                      21903
New York                       209338
North Carolina                 116730
North Dakota                    10059
Ohio                           129191
Oklahoma                        47623
Oregon                          39820
Pennsylvania                   130693
Rhode Island                    10101
South Carolina                  55704
South Dakota                    10960
Tennessee                       78689
Texas                          368190
Utah                            45702
Vermont                          5133
Virginia                        94749
Washington                      83086
West Virginia                   17323
Wisconsin                       60594
Wyoming                          6128

In [7]:
total_births_df['Number of Births'] =  pd.to_numeric(total_births_df['Number of Births'])
death_div_births = (maternal_deaths_df["Number Maternal Deaths"] / total_births_df["Number of Births"])
death_div_births_mult = death_div_births * 100000
maternal_mortality_df = pd.DataFrame(data=death_div_births_mult, columns=['Maternal_Mortality'])
maternal_mortality_df

                      Maternal_Mortality
Location
Alabama                       109.285826
Alaska                         84.486218
Arizona                        87.072920
Arkansas                      124.819154
California                     32.123048
Colorado                       43.906723
Connecticut                    53.795577
Delaware                       48.113934
District of Columbia           78.882128
Florida                        67.248213
Georgia                        88.182701
Hawaii                         44.345898
Idaho                          51.084382
Illinois                       40.510735
Indiana                        86.496388
Iowa                           38.766129
Kansas                         66.907145
Kentucky                      121.932337
Louisiana                      97.683505
Maine                          25.998787
Maryland                       56.889459
Massachusetts                  45.161679
Michigan                       60.533851
Minnesota                      29.948142
Mississippi                    93.028501
Missouri                       77.938948
Montana                        74.135854
Nebraska                       86.451772
Nevada                         59.430066
New Hampshire                  16.962090
New Jersey                     73.503890
New Mexico                     45.655846
New York                       63.533615
North Carolina                 62.537480
North Dakota                   69.589422
Ohio                           65.794057
Oklahoma                       75.593726
Oregon                         45.203415
Pennsylvania                   45.909115
Rhode Island                   49.500050
South Carolina                 87.964958
South Dakota                   63.868613
Tennessee                     105.478529
Texas                          69.800918
Utah                           37.197497
Vermont                        19.481785
Virginia                       68.602307
Washington                     62.585755
West Virginia                  69.272066
Wisconsin                      28.055583
Wyoming                        48.955614

In [8]:
population_df = pd.read_csv("Population_Distribution_by_Sex.csv", 
                            skiprows=[0,1,3,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69], 
                            index_col='Location')
population_df = population_df.drop(columns=['Footnotes', 'Male', 'Female'])
population_df = population_df.rename(columns={"Total":"Population"})
population_df

                      Population
Location
Alabama                  4767100
Alaska                    701700
Arizona                  7098000
Arkansas                 2922500
California              38642700
Colorado                 5611800
Connecticut              3453300
Delaware                  940300
District of Columbia      671300
Florida                 20992000
Georgia                 10294000
Hawaii                   1343000
Idaho                    1750900
Illinois                12362300
Indiana                  6511800
Iowa                     3060200
Kansas                   2811200
Kentucky                 4319300
Louisiana                4498600
Maine                    1302300
Maryland                 5875500
Massachusetts            6650800
Michigan                 9765600
Minnesota                5514800
Mississippi              2867100
Missouri                 5939900
Montana                  1039400
Nebraska                 1873600
Nevada                   3029700
New Hampshire            1314000
New Jersey               8699400
New Mexico               2041400
New York                18908300
North Carolina          10139700
North Dakota              731000
Ohio                    11351500
Oklahoma                 3826900
Oregon                   4128900
Pennsylvania            12377600
Rhode Island             1017100
South Carolina           4984200
South Dakota              851300
Tennessee                6640900
Texas                   28286200
Utah                     3154100
Vermont                   598100
Virginia                 8185100
Washington               7423900
West Virginia            1739000
Wisconsin                5677100
Wyoming                   562700

In [9]:
no_doctor_visit_df = pd.read_csv("Report_Not_Seeing_Doctor_in_Past_12_Months_Due_to_Cost.csv", 
                                 skiprows=[0,1,3,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75], 
                                 index_col='Location')
no_doctor_visit_df = no_doctor_visit_df.drop(columns='Footnotes')
no_doctor_visit_df = no_doctor_visit_df.rename(columns={"All Women": "No_Doctor_Visits"})
no_doctor_visit_df

                      No_Doctor_Visits
Location
Alabama                           0.12
Alaska                            0.12
Arizona                           0.11
Arkansas                          0.12
California                        0.09
Colorado                          0.11
Connecticut                       0.07
Delaware                          0.09
District of Columbia              0.06
Florida                           0.14
Georgia                           0.16
Hawaii                            0.06
Idaho                             0.10
Illinois                          0.10
Indiana                           0.10
Iowa                              0.07
Kansas                            0.10
Kentucky                          0.09
Louisiana                         0.09
Maine                             0.08
Maryland                          0.08
Massachusetts                     0.06
Michigan                          0.08
Minnesota                         0.08
Mississippi                       0.13
Missouri                          0.12
Montana                           0.09
Nebraska                          0.09
Nevada                            0.12
New Hampshire                     0.09
New Jersey                        0.10
New Mexico                        0.09
New York                          0.08
North Carolina                    0.12
North Dakota                      0.07
Ohio                              0.09
Oklahoma                          0.15
Oregon                            0.11
Pennsylvania                      0.08
Rhode Island                      0.07
South Carolina                    0.12
South Dakota                      0.07
Tennessee                         0.12
Texas                             0.17
Utah                              0.10
Vermont                           0.07
Virginia                          0.10
Washington                        0.09
West Virginia                     0.10
Wisconsin                         0.08
Wyoming                           0.12

In [10]:
mammogram_df = pd.read_csv("Reported_Mammogram_2_Years.csv", 
                           skiprows=[0,1,3,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73], 
                           index_col='Location')
mammogram_df = mammogram_df.drop(columns='Footnotes')
mammogram_df = mammogram_df.rename(columns={"All Women": "Mammogram"})
mammogram_df

                      Mammogram
Location
Alabama                    0.74
Alaska                     0.63
Arizona                    0.68
Arkansas                   0.70
California                 0.68
Colorado                   0.67
Connecticut                0.78
Delaware                   0.74
District of Columbia       0.74
Florida                    0.74
Georgia                    0.71
Hawaii                     0.78
Idaho                      0.65
Illinois                   0.74
Indiana                    0.69
Iowa                       0.76
Kansas                     0.69
Kentucky                   0.71
Louisiana                  0.78
Maine                      0.77
Maryland                   0.75
Massachusetts              0.80
Michigan                   0.74
Minnesota                  0.73
Mississippi                0.71
Missouri                   0.71
Montana                    0.68
Nebraska                   0.70
Nevada                     0.69
New Hampshire              0.74
New Jersey                 0.73
New Mexico                 0.65
New York                   0.77
North Carolina             0.75
North Dakota               0.75
Ohio                       0.72
Oklahoma                   0.68
Oregon                     0.72
Pennsylvania               0.74
Rhode Island               0.81
South Carolina             0.76
South Dakota               0.75
Tennessee                  0.73
Texas                      0.69
Utah                       0.64
Vermont                    0.68
Virginia                   0.75
Washington                 0.68
West Virginia              0.74
Wisconsin                  0.75
Wyoming                    0.64

In [11]:
no_doctor_df = pd.read_csv("Reported_No_Personal_Doctor_or_Health_Care_Provider.csv", 
                           skiprows=[0,1,3,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75], 
                           index_col='Location')
no_doctor_df = no_doctor_df.drop(columns='Footnotes')
no_doctor_df = no_doctor_df.rename(columns={"All Women": "No_Provider"})
no_doctor_df

                      No_Provider
Location
Alabama                      0.13
Alaska                       0.23
Arizona                      0.19
Arkansas                     0.13
California                   0.19
Colorado                     0.17
Connecticut                  0.10
Delaware                     0.12
District of Columbia         0.15
Florida                      0.20
Georgia                      0.17
Hawaii                       0.10
Idaho                        0.15
Illinois                     0.15
Indiana                      0.12
Iowa                         0.10
Kansas                       0.13
Kentucky                     0.12
Louisiana                    0.12
Maine                        0.08
Maryland                     0.10
Massachusetts                0.07
Michigan                     0.08
Minnesota                    0.15
Mississippi                  0.13
Missouri                     0.15
Montana                      0.17
Nebraska                     0.12
Nevada                       0.24
New Hampshire                0.07
New Jersey                   0.13
New Mexico                   0.19
New York                     0.15
North Carolina               0.14
North Dakota                 0.19
Ohio                         0.13
Oklahoma                     0.16
Oregon                       0.14
Pennsylvania                 0.09
Rhode Island                 0.08
South Carolina               0.14
South Dakota                 0.13
Tennessee                    0.14
Texas                        0.25
Utah                         0.17
Vermont                      0.08
Virginia                     0.15
Washington                   0.16
West Virginia                0.11
Wisconsin                    0.09
Wyoming                      0.20

In [12]:
pap_smear_df = pd.read_csv("Reported_Pap_Smear_3_Years.csv", 
                           skiprows=[0,1,3,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71], 
                           index_col='Location')
pap_smear_df = pap_smear_df.drop(columns='Footnotes')
pap_smear_df = pap_smear_df.rename(columns={"All Women": "Pap_Smear"})
pap_smear_df

                      Pap_Smear
Location
Alabama                    0.74
Alaska                     0.65
Arizona                    0.69
Arkansas                   0.68
California                 0.74
Colorado                   0.69
Connecticut                0.80
Delaware                   0.75
District of Columbia       0.80
Florida                    0.73
Georgia                    0.73
Hawaii                     0.73
Idaho                      0.64
Illinois                   0.73
Indiana                    0.69
Iowa                       0.70
Kansas                     0.68
Kentucky                   0.72
Louisiana                  0.75
Maine                      0.73
Maryland                   0.76
Massachusetts              0.77
Michigan                   0.73
Minnesota                  0.71
Mississippi                0.77
Missouri                   0.71
Montana                    0.67
Nebraska                   0.69
Nevada                     0.69
New Hampshire              0.72
New Jersey                 0.78
New Mexico                 0.69
New York                   0.78
North Carolina             0.75
North Dakota               0.66
Ohio                       0.71
Oklahoma                   0.67
Oregon                     0.72
Pennsylvania               0.74
Rhode Island               0.78
South Carolina             0.71
South Dakota               0.70
Tennessee                  0.72
Texas                      0.70
Utah                       0.64
Vermont                    0.70
Virginia                   0.75
Washington                 0.68
West Virginia              0.72
Wisconsin                  0.72
Wyoming                    0.64

In [13]:
ins_contraceptives_df = pd.read_csv("State_Requirements_Ins_Coverage_Contraceptives.csv",
                                   skiprows=[0,1,3,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74],
                                   index_col='Location')
ins_contraceptives_df = ins_contraceptives_df.drop(columns="Footnotes")
ins_contraceptives_df = ins_contraceptives_df.rename(columns={"State Requires Coverage of Prescription Contraception": "Prescription_Contraception", 
                                                             "State Requires Coverage of Over-the-counter Methods": "OTC_Methods",
                                                             "State Requires Coverage of Male Sterilization": "Male_Sterilization",
                                                             "State Requires Coverage of Female Sterilization": "Female_Sterilization",
                                                             "State Prohibits cost sharing": "Cost_Sharing"})

ins_contraceptives_df

,Prescription_Contraception,OTC_Methods,Male_Sterilization,Female_Sterilization,Cost_Sharing
Location,,,,,
Alabama,No,No,No,No,No
Alaska,No,No,No,No,No
Arizona,Yes,No,No,No,No
Arkansas,Yes,No,No,No,No
California,Yes,Yes,No,Yes,Yes
Colorado,Yes,No,No,No,No
Connecticut,Yes,Yes,No,Yes,Yes
Delaware,Yes,Yes,No,Yes,Yes
District of Columbia,Yes,Yes,No,Yes,Yes
Florida,No,No,No,No,No
Georgia,Yes,No,No,No,No
Hawaii,Yes,No,No,No,No
Idaho,No,No,No,No,No
Illinois,Yes,Yes,Yes,Yes,Yes
Indiana,No,No,No,No,No
Iowa,Yes,No,No,No,No
Kansas,No,No,No,No,No
Kentucky,No,No,No,No,No
Louisiana,No,No,No,No,No
Maine,Yes,No,No,Yes,Yes
Maryland,Yes,Yes,Yes,No,Yes
Massachusetts,Yes,Yes,No,Yes,Yes
Michigan,Yes,No,No,No,No
Minnesota,No,No,No,No,No
Mississippi,No,No,No,No,No
Missouri,Yes,No,No,No,No
Montana,Yes,No,No,No,No
Nebraska,No,No,No,No,No
Nevada,Yes,Yes,No,Yes,Yes
New Hampshire,Yes,No,No,No,Yes
New Jersey,Yes,Yes,Yes,Yes,Yes
New Mexico,Yes,Yes,Yes,Yes,Yes
New York,Yes,Yes,Yes,Yes,Yes
North Carolina,Yes,No,No,No,No
North Dakota,No,No,No,No,No
Ohio,No,No,No,No,No
Oklahoma,No,No,No,No,No
Oregon,Yes,Yes,Yes,Yes,Yes
Pennsylvania,No,No,No,No,No
Rhode Island,Yes,No,No,No,No
South Carolina,No,No,No,No,No
South Dakota,No,No,No,No,No
Tennessee,No,No,No,No,No
Texas,No,No,No,No,No
Utah,No,No,No,No,No
Vermont,Yes,No,Yes,Yes,Yes
Virginia,Yes,No,No,Yes,Yes
Washington,Yes,Yes,Yes,Yes,Yes
West Virginia,Yes,No,No,No,No
Wisconsin,Yes,No,No,No,No
Wyoming,No,No,No,No,No

In [14]:
teen_birth_df = pd.read_csv("Teen_Birth_Rate.csv", 
                           skiprows=[0,1,3,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72], 
                           index_col='Location')
teen_birth_df = teen_birth_df.drop(columns="Footnotes")
teen_birth_df = teen_birth_df.rename(columns={"Teen Birth Rate per 1,000": "Teen_Births"})
teen_birth_df

                      Teen_Births
Location
Alabama                      24.8
Alaska                       17.7
Arizona                      16.6
Arkansas                     27.8
California                   11.0
Colorado                     12.5
Connecticut                   7.6
Delaware                     14.6
District of Columbia         15.6
Florida                      15.2
Georgia                      18.2
Hawaii                       13.0
Idaho                        14.6
Illinois                     13.6
Indiana                      18.7
Iowa                         13.3
Kansas                       18.1
Kentucky                     23.8
Louisiana                    25.7
Maine                        10.6
Maryland                     13.1
Massachusetts                 6.1
Michigan                     13.5
Minnesota                     9.1
Mississippi                  27.9
Missouri                     18.8
Montana                      13.2
Nebraska                     15.1
Nevada                       16.8
New Hampshire                 6.6
New Jersey                    9.2
New Mexico                   21.9
New York                     10.0
North Carolina               17.3
North Dakota                 13.7
Ohio                         17.6
Oklahoma                     25.0
Oregon                       10.1
Pennsylvania                 12.6
Rhode Island                  9.4
South Carolina               19.3
South Dakota                 18.7
Tennessee                    23.3
Texas                        22.4
Utah                         10.8
Vermont                       7.0
Virginia                     13.1
Washington                   11.3
West Virginia                22.5
Wisconsin                    11.5
Wyoming                      18.1

In [15]:
poverty_df = pd.read_csv("poverty_pop_distribution.csv", 
                           skiprows=[0,1,3,55,56,57,58,59,60,61,62,63,64], 
                           index_col='Location')
poverty_df = poverty_df.drop(columns=["Total", "200-399%", "400%+"])
poverty_df = poverty_df.rename(columns={"Under 100%": "poverty_under_100", "100-199%": "poverty_100_to_199"})
poverty_df

                      poverty_under_100  poverty_100_to_199
Location
Alabama                           0.151               0.181
Alaska                            0.136               0.149
Arizona                           0.110               0.188
Arkansas                          0.142               0.192
California                        0.111               0.161
Colorado                          0.095               0.124
Connecticut                       0.112               0.116
Delaware                          0.106               0.186
District of Columbia              0.167               0.104
Florida                           0.134               0.191
Georgia                           0.134               0.186
Hawaii                            0.110               0.130
Idaho                             0.093               0.177
Illinois                          0.080               0.149
Indiana                           0.122               0.145
Iowa                              0.091               0.158
Kansas                            0.093               0.160
Kentucky                          0.141               0.209
Louisiana                         0.157               0.200
Maine                             0.081               0.179
Maryland                          0.092               0.118
Massachusetts                     0.086               0.114
Michigan                          0.112               0.138
Minnesota                         0.084               0.129
Mississippi                       0.176               0.231
Missouri                          0.109               0.170
Montana                           0.112               0.184
Nebraska                          0.083               0.186
Nevada                            0.130               0.189
New Hampshire                     0.062               0.095
New Jersey                        0.082               0.120
New Mexico                        0.165               0.243
New York                          0.119               0.151
North Carolina                    0.139               0.176
North Dakota                      0.110               0.163
Ohio                              0.129               0.173
Oklahoma                          0.156               0.210
Oregon                            0.095               0.153
Pennsylvania                      0.107               0.134
Rhode Island                      0.091               0.147
South Carolina                    0.134               0.156
South Dakota                      0.116               0.131
Tennessee                         0.134               0.193
Texas                             0.141               0.174
Utah                              0.076               0.125
Vermont                           0.089               0.135
Virginia                          0.078               0.129
Washington                        0.084               0.122
West Virginia                     0.142               0.191
Wisconsin                         0.082               0.137
Wyoming                           0.100               0.182

In [16]:
add_poverty_df = (poverty_df['poverty_under_100'] + poverty_df['poverty_100_to_199'])
new_poverty_df = pd.DataFrame(data=add_poverty_df, columns=['poverty_under_200'])
new_poverty_df

                      poverty_under_200
Location
Alabama                           0.332
Alaska                            0.285
Arizona                           0.298
Arkansas                          0.334
California                        0.272
Colorado                          0.219
Connecticut                       0.228
Delaware                          0.292
District of Columbia              0.271
Florida                           0.325
Georgia                           0.320
Hawaii                            0.240
Idaho                             0.270
Illinois                          0.229
Indiana                           0.267
Iowa                              0.249
Kansas                            0.253
Kentucky                          0.350
Louisiana                         0.357
Maine                             0.260
Maryland                          0.210
Massachusetts                     0.200
Michigan                          0.250
Minnesota                         0.213
Mississippi                       0.407
Missouri                          0.279
Montana                           0.296
Nebraska                          0.269
Nevada                            0.319
New Hampshire                     0.157
New Jersey                        0.202
New Mexico                        0.408
New York                          0.270
North Carolina                    0.315
North Dakota                      0.273
Ohio                              0.302
Oklahoma                          0.366
Oregon                            0.248
Pennsylvania                      0.241
Rhode Island                      0.238
South Carolina                    0.290
South Dakota                      0.247
Tennessee                         0.327
Texas                             0.315
Utah                              0.201
Vermont                           0.224
Virginia                          0.207
Washington                        0.206
West Virginia                     0.333
Wisconsin                         0.219
Wyoming                           0.282

In [17]:
#https://stackoverflow.com/questions/44327999/python-pandas-merge-multiple-dataframes
data_frames = [abortion_status_df, CHC_df, ins_df, maternal_mortality_df, population_df, no_doctor_visit_df, 
              mammogram_df, no_doctor_df, pap_smear_df, ins_contraceptives_df, teen_birth_df, new_poverty_df]

In [18]:
from functools import reduce

In [19]:
df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['Location'],
                                            how='outer'), data_frames)

In [20]:
df_merged.index.names = ['State']

In [21]:
df_merged.head(5)

,Abortion_Status,Total_Community_Health_Centers,Uninsured,Total_Insured,Maternal_Mortality,Population,No_Doctor_Visits,Mammogram,No_Provider,Pap_Smear,Prescription_Contraception,OTC_Methods,Male_Sterilization,Female_Sterilization,Cost_Sharing,Teen_Births,poverty_under_200
State,,,,,,,,,,,,,,,,,
Alabama,Abortion Ban In Effect,17,165700,1462900,109.285826,4767100,0.12,0.74,0.13,0.74,No,No,No,No,No,24.8,0.332
Alaska,Abortion Available,27,29200,207200,84.486218,701700,0.12,0.63,0.23,0.65,No,No,No,No,No,17.7,0.285
Arizona,Status of pre-Roe ban unclear,23,309000,2132900,87.072920,7098000,0.11,0.68,0.19,0.69,Yes,No,No,No,No,16.6,0.298
Arkansas,Abortion Ban In Effect,12,83800,865900,124.819154,2922500,0.12,0.70,0.13,0.68,Yes,No,No,No,No,27.8,0.334
California,Abortion Available,175,1034300,11885100,32.123048,38642700,0.09,0.68,0.19,0.74,Yes,Yes,No,Yes,Yes,11.0,0.272

In [22]:
df_merged.dtypes

Abortion_Status                    object
Total_Community_Health_Centers      int64
Uninsured                           int64
Total_Insured                       int64
Maternal_Mortality                float64
Population                          int64
No_Doctor_Visits                  float64
Mammogram                         float64
No_Provider                       float64
Pap_Smear                         float64
Prescription_Contraception         object
OTC_Methods                        object
Male_Sterilization                 object
Female_Sterilization               object
Cost_Sharing                       object
Teen_Births                       float64
poverty_under_200                 float64
dtype: object

In [23]:
pd.DataFrame.to_csv(df_merged, 'merged.csv', sep=',', na_rep='.', index=True)

In [24]:
db_string = f"postgresql://postgres:{db_password}@127.0.0.1:5433/Reproducitve_Access"

In [25]:
engine = create_engine(db_string)

In [26]:
df_merged.to_sql(name='states_data', con=engine)