In [47]:
import numpy as np
import pandas as pd
from pathlib import Path

In [48]:
# Loading clustered dataset
file = "Resources/MLM/clustered_data.csv"
clustered_df = pd.read_csv(file, index_col=0)
clustered_df.head(10)

,abortion_status,total_community_health_centers,uninsured,total_insured,maternal_mortality,population,no_doctor_visits,mammogram,no_provider,pap_smear,...,abortions_residence_state,no_services,few_services,restricted_services,full_service,chc_per_capita,PC 1,PC 2,PC 3,Class
state,,,,,,,,,,,,,,,,,,,,,
Alabama,Abortion Ban In Effect,17,165700,1462900,109.285826,4767100,0.12,0.74,0.13,0.74,...,9060,8,44,5,0,0.356611,-3.389517,1.468611,1.450318,0
Alaska,Abortion Available,27,29200,207200,84.486218,701700,0.12,0.63,0.23,0.65,...,1320,3,7,0,4,3.847798,-2.985732,-0.654379,1.727523,0
Arizona,Status of pre-Roe ban unclear,23,309000,2132900,87.072920,7098000,0.11,0.68,0.19,0.69,...,13820,19,28,7,0,0.324035,-1.623217,1.289916,-0.185999,0
Arkansas,Abortion Ban In Effect,12,83800,865900,124.819154,2922500,0.12,0.70,0.13,0.68,...,4510,9,31,3,0,0.410607,-3.225696,0.563117,1.934296,0
California,Abortion Available,175,1034300,11885100,32.123048,38642700,0.09,0.68,0.19,0.74,...,152400,51,97,0,124,0.452867,10.762057,8.750072,-1.291324,2
Colorado,Abortion Available,19,204300,1758600,43.906723,5611800,0.11,0.67,0.17,0.69,...,11830,17,34,0,15,0.338572,-0.276557,-0.145824,-1.260018,1
Connecticut,Abortion Available,16,58100,1038000,53.795577,3453300,0.07,0.78,0.10,0.80,...,11460,12,8,0,18,0.463325,3.535804,-3.156709,-0.614361,4
Delaware,Abortion Available,3,24800,295800,48.113934,940300,0.09,0.74,0.12,0.75,...,2870,10,0,0,2,0.319047,2.044858,-3.345393,1.189281,4
District of Columbia,Abortion Available,8,7600,251600,78.882128,671300,0.06,0.74,0.15,0.80,...,5010,2,0,0,2,1.191718,2.150158,-3.521315,1.427751,4
Florida,"Abortion available, pre-viability gestational ...",47,1011800,6381600,67.248213,20992000,0.14,0.74,0.20,0.73,...,73830,22,129,0,48,0.223895,1.098599,6.575453,-1.398009,3

In [49]:
chc_df = clustered_df['chc_per_capita'].to_frame()
chc_df['total_community_health_centers'] = clustered_df['total_community_health_centers']
chc_df['population'] = clustered_df['population']
chc_df['Class'] = clustered_df['Class']

chc_df.head()

            chc_per_capita  total_community_health_centers  population  Class
state
Alabama           0.356611                              17     4767100      0
Alaska            3.847798                              27      701700      0
Arizona           0.324035                              23     7098000      0
Arkansas          0.410607                              12     2922500      0
California        0.452867                             175    38642700      2

In [50]:
base_df = chc_df.loc[chc_df['Class']==4]
base_df.head()

,chc_per_capita,total_community_health_centers,population,Class
state,,,,
Connecticut,0.463325,16,3453300,4
Delaware,0.319047,3,940300,4
District of Columbia,1.191718,8,671300,4
Illinois,0.364010,45,12362300,4
Maine,1.382170,18,1302300,4

In [51]:
base_df['chc_per_capita'].describe()

count    14.000000
mean      0.651802
std       0.490090
min       0.264053
25%       0.318000
50%       0.413667
75%       0.769478
max       1.839157
Name: chc_per_capita, dtype: float64

In [44]:
# recommended_chc = chc_df.loc[chc_df['Class']!=4]
# recommended_chc

,chc_per_capita,total_community_health_centers,population,Class
state,,,,
Alabama,0.356611,17,4767100,0
Alaska,3.847798,27,701700,0
Arizona,0.324035,23,7098000,0
Arkansas,0.410607,12,2922500,0
California,0.452867,175,38642700,2
Colorado,0.338572,19,5611800,1
Florida,0.223895,47,20992000,3
Georgia,0.340004,35,10294000,0
Hawaii,1.042442,14,1343000,1
Idaho,0.799589,14,1750900,0
Indiana,0.414632,27,6511800,0
Iowa,0.457486,14,3060200,1
Kansas,0.675868,19,2811200,0
Kentucky,0.578797,25,4319300,0
Louisiana,0.800249,36,4498600,0
Michigan,0.399361,39,9765600,1
Minnesota,0.290128,16,5514800,1
Mississippi,0.697569,20,2867100,0
Missouri,0.471388,28,5939900,0
Montana,1.346931,14,1039400,0
Nebraska,0.373612,7,1873600,0
New Hampshire,0.761035,10,1314000,1
New York,0.333187,63,18908300,2
North Carolina,0.384627,39,10139700,1
North Dakota,0.547196,4,731000,0
Ohio,0.449280,51,11351500,0
Oklahoma,0.548747,21,3826900,0
Pennsylvania,0.339323,42,12377600,1
Rhode Island,0.786550,8,1017100,1
South Carolina,0.461458,23,4984200,0
South Dakota,0.469870,4,851300,0
Tennessee,0.436688,29,6640900,0
Texas,0.254541,72,28286200,3
Utah,0.412162,13,3154100,0
West Virginia,1.610121,28,1739000,0
Wisconsin,0.281834,16,5677100,1
Wyoming,1.066288,6,562700,0

In [52]:
chc_df['rec_add_chc'] = (chc_df['population'] * 0.6518 / 100000).round() - chc_df['total_community_health_centers']
chc_df.sort_values('rec_add_chc', ascending=False)

,chc_per_capita,total_community_health_centers,population,Class,rec_add_chc
state,,,,,
Texas,0.254541,72,28286200,3,112.0
Florida,0.223895,47,20992000,3,90.0
California,0.452867,175,38642700,2,77.0
New York,0.333187,63,18908300,2,60.0
Pennsylvania,0.339323,42,12377600,1,39.0
Illinois,0.364010,45,12362300,4,36.0
New Jersey,0.264386,23,8699400,4,34.0
Georgia,0.340004,35,10294000,0,32.0
Virginia,0.317650,26,8185100,4,27.0
North Carolina,0.384627,39,10139700,1,27.0
Michigan,0.399361,39,9765600,1,25.0
Ohio,0.449280,51,11351500,0,23.0
Arizona,0.324035,23,7098000,0,23.0
Washington,0.363690,27,7423900,4,21.0
Maryland,0.289337,17,5875500,4,21.0
Wisconsin,0.281834,16,5677100,1,21.0
Minnesota,0.290128,16,5514800,1,20.0
Colorado,0.338572,19,5611800,1,18.0
Indiana,0.414632,27,6511800,0,15.0
Alabama,0.356611,17,4767100,0,14.0
Tennessee,0.436688,29,6640900,0,14.0
Nevada,0.264053,8,3029700,4,12.0
Missouri,0.471388,28,5939900,0,11.0
South Carolina,0.461458,23,4984200,0,9.0
Utah,0.412162,13,3154100,0,8.0
Arkansas,0.410607,12,2922500,0,7.0
Connecticut,0.463325,16,3453300,4,7.0
Massachusetts,0.556324,37,6650800,4,6.0
Iowa,0.457486,14,3060200,1,6.0
Nebraska,0.373612,7,1873600,0,5.0
Oklahoma,0.548747,21,3826900,0,4.0
Delaware,0.319047,3,940300,4,3.0
Kentucky,0.578797,25,4319300,0,3.0
South Dakota,0.469870,4,851300,0,2.0
North Dakota,0.547196,4,731000,0,1.0
Rhode Island,0.786550,8,1017100,1,-1.0
New Hampshire,0.761035,10,1314000,1,-1.0
Kansas,0.675868,19,2811200,0,-1.0
Mississippi,0.697569,20,2867100,0,-1.0
Wyoming,1.066288,6,562700,0,-2.0
Idaho,0.799589,14,1750900,0,-3.0
New Mexico,0.783776,16,2041400,4,-3.0
Oregon,0.726586,30,4128900,4,-3.0
District of Columbia,1.191718,8,671300,4,-4.0
Hawaii,1.042442,14,1343000,1,-5.0
Louisiana,0.800249,36,4498600,0,-7.0
Vermont,1.839157,11,598100,4,-7.0
Montana,1.346931,14,1039400,0,-7.0
Maine,1.382170,18,1302300,4,-10.0
West Virginia,1.610121,28,1739000,0,-17.0
Alaska,3.847798,27,701700,0,-22.0